### ISSUE TITLE
Does not forward headers

### ISSUE THREAD

**Issue by john-doherty** [orca-scan/express-request-transfer#1]
If the destination route _(the one that accepts the transfer)_ sets HTTP headers such as content type, they are not passed on to the client. I would expect that to happen. 

Might be best to check the docs for Microsofts Server.Transfer in C#, see how that does it and try to keep it consistent. If it is expect behaviour, we need to ensure we make that clear from the docs

**Comment by Phunky** [comment]
Also to note that HTTP Status code is also not forwarded on.
